global:
  resolve_timeout: 5m

route:
  receiver: "null"
  group_by:
    - alertname
    - alertgroup
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 4h

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal:
      - alertname
      - service_name
      - queue

receivers:
  - name: "null"
