# config.yaml
issuer: http://localhost:5556/dex
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']
  allowedHeaders: ['x-requested-with']
staticClients:
  - id: daytona
    redirectURIs:
      - 'http://localhost:3300'
      - 'http://localhost:3300/api/oauth2-redirect.html'
      - 'http://localhost:3009/callback'
      - 'http://proxy.localhost:4000/callback'
    name: 'Daytona'
    public: true
enablePasswordDB: true
staticPasswords:
  - email: 'dev@daytona.io'
    hash: '__DAYTONA_DEX_PASSWORD_HASH__'
    username: 'admin'
    userID: '1234'
