receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp/vector:
    endpoint: vector:4317
    tls:
      insecure: true

  otlp/vector_traces:
    endpoint: vector:5317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/vector_traces]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/vector]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/vector]
